package notify

import (
	"bytes"
	"context"
	"fmt"
	"net/smtp"
	"os"
	"strconv"
	"strings"

	"github.com/jaykbpark/ats-job-monitor/internal/store"
)

type SMTPConfig struct {
	Host     string
	Port     int
	Username string
	Password string
	From     string
}

type MailSender interface {
	Send(from string, to []string, msg []byte) error
}

type smtpSender struct {
	addr string
	auth smtp.Auth
}

func (s smtpSender) Send(from string, to []string, msg []byte) error {
	return smtp.SendMail(s.addr, s.auth, from, to, msg)
}

type SMTPSink struct {
	config SMTPConfig
	sender MailSender
}

func NewSMTPSink(config SMTPConfig) (*SMTPSink, error) {
	normalized, err := normalizeSMTPConfig(config)
	if err != nil {
		return nil, err
	}

	var auth smtp.Auth
	if normalized.Username != "" {
		auth = smtp.PlainAuth("", normalized.Username, normalized.Password, normalized.Host)
	}

	return &SMTPSink{
		config: normalized,
		sender: smtpSender{
			addr: fmt.Sprintf("%s:%d", normalized.Host, normalized.Port),
			auth: auth,
		},
	}, nil
}

func NewSMTPSinkFromEnv() (*SMTPSink, error) {
	port := 587
	rawPort := strings.TrimSpace(os.Getenv("ATS_JOB_MONITOR_SMTP_PORT"))
	if rawPort != "" {
		parsed, err := strconv.Atoi(rawPort)
		if err != nil || parsed <= 0 {
			return nil, fmt.Errorf("ATS_JOB_MONITOR_SMTP_PORT must be a positive integer")
		}
		port = parsed
	}

	return NewSMTPSink(SMTPConfig{
		Host:     strings.TrimSpace(os.Getenv("ATS_JOB_MONITOR_SMTP_HOST")),
		Port:     port,
		Username: strings.TrimSpace(os.Getenv("ATS_JOB_MONITOR_SMTP_USERNAME")),
		Password: os.Getenv("ATS_JOB_MONITOR_SMTP_PASSWORD"),
		From:     strings.TrimSpace(os.Getenv("ATS_JOB_MONITOR_SMTP_FROM")),
	})
}

func (s *SMTPSink) Deliver(ctx context.Context, notification store.NotificationRecord) error {
	if err := ctx.Err(); err != nil {
		return err
	}

	recipient := strings.TrimSpace(notification.NotificationEmail)
	if recipient == "" {
		return fmt.Errorf("notification email is required for email delivery")
	}

	message, err := buildEmailMessage(s.config.From, recipient, notification)
	if err != nil {
		return err
	}

	if err := s.sender.Send(s.config.From, []string{recipient}, message); err != nil {
		return fmt.Errorf("send email notification: %w", err)
	}

	return nil
}

func buildEmailMessage(from string, to string, notification store.NotificationRecord) ([]byte, error) {
	subject := fmt.Sprintf("[ATS Job Monitor] New matching role: %s", strings.TrimSpace(notification.JobTitle))
	bodyLines := []string{
		fmt.Sprintf("Watch target: %s", defaultString(notification.WatchTargetName, strconv.FormatInt(notification.WatchTargetID, 10))),
		fmt.Sprintf("Role: %s", notification.JobTitle),
		fmt.Sprintf("URL: %s", notification.JobURL),
	}
	if strings.TrimSpace(notification.ExternalJobID) != "" {
		bodyLines = append(bodyLines, fmt.Sprintf("External job ID: %s", notification.ExternalJobID))
	}
	bodyLines = append(bodyLines, "", "This notification was generated by ats-job-monitor.")

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("From: %s\r\n", from))
	buf.WriteString(fmt.Sprintf("To: %s\r\n", to))
	buf.WriteString(fmt.Sprintf("Subject: %s\r\n", subject))
	buf.WriteString("MIME-Version: 1.0\r\n")
	buf.WriteString("Content-Type: text/plain; charset=UTF-8\r\n")
	buf.WriteString("\r\n")
	buf.WriteString(strings.Join(bodyLines, "\r\n"))
	buf.WriteString("\r\n")

	return buf.Bytes(), nil
}

func normalizeSMTPConfig(config SMTPConfig) (SMTPConfig, error) {
	normalized := SMTPConfig{
		Host:     strings.TrimSpace(config.Host),
		Port:     config.Port,
		Username: strings.TrimSpace(config.Username),
		Password: config.Password,
		From:     strings.TrimSpace(config.From),
	}

	if normalized.Host == "" {
		return SMTPConfig{}, fmt.Errorf("ATS_JOB_MONITOR_SMTP_HOST is required")
	}
	if normalized.Port <= 0 {
		return SMTPConfig{}, fmt.Errorf("ATS_JOB_MONITOR_SMTP_PORT must be a positive integer")
	}
	if normalized.From == "" {
		return SMTPConfig{}, fmt.Errorf("ATS_JOB_MONITOR_SMTP_FROM is required")
	}
	if normalized.Password != "" && normalized.Username == "" {
		return SMTPConfig{}, fmt.Errorf("ATS_JOB_MONITOR_SMTP_USERNAME is required when ATS_JOB_MONITOR_SMTP_PASSWORD is set")
	}

	return normalized, nil
}

func defaultString(value string, fallback string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return fallback
	}

	return trimmed
}
